name: Formatting
on: [pull_request]

jobs:
  formatting:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    container:
      image: python:3.10

    steps:
      - uses: actions/checkout@v2
      - name: Install virtualenv and other prerequisites
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install wheel
          pip install -r requirements.txt
      - name: Check formatting
        run: |
          set -e
          . venv/bin/activate
          black --check --line-length=80 src/namespaced_enums.py tests/test_namespaced_enums.py 
