name: Tests-3.10
on: [pull_request]

jobs:
  tests-310:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    container:
      image: python:3.10

    steps:
      - uses: actions/checkout@v2
      - name: Install virtualenv and other prerequisites
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install wheel
          pip install -r requirements.txt
      - name: Run tests for Python 3.10
        run: |
          set -e
          . venv/bin/activate
          pytest .
